apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: front-end
    name: front-end
    version: v0.1.0
  name: front-end
  namespace: sock-shop
spec:
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 8079
  selector:
    app: front-end
    name: front-end
    version: v0.1.0
  type: LoadBalancer
